# Generated by Django 2.1.7 on 2019-03-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published_at',
            field=models.DateField(),
        ),
    ]
